version: 0.2

phases:
  pre_build:
    commands:
      - pip3 install awscli --upgrade --user
      - npm install -g yarn
  build:
    commands:
      - yarn install
      - CTF_SPACE_ID=ypf8ol9cl3g0 CTF_CDA_ACCESS_TOKEN=4yBDLGB16xOjhMm0xYPSBkpemdLemcck5HfoI-ZbQrI yarn run generate
  post_build:
    commands:
      - yarn run deploy
