version: '3'

services:

  node:
    image: node:10.14.1-alpine
    tty: true
    working_dir: /var/www
    command: yarn run dev
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
    environment:
      - NODE_ENV=development
      - CTF_SPACE_ID=ypf8ol9cl3g0
      - CTF_CDA_ACCESS_TOKEN=4yBDLGB16xOjhMm0xYPSBkpemdLemcck5HfoI-ZbQrI
      - HOST=0.0.0.0
